export PATH="/usr/local/bin:$PATH"
export NVM_DIR="$HOME/.nvm"
export PATH="$PATH:/usr/local/smlnj/bin"
. "$(brew --prefix nvm)/nvm.sh"
export PATH=$PATH:$HOME/bin
export PGDATA=/Library/PostgreSQL/9.5/data

alias l='ls -la'
